cranci1/Sora

- Sora/Info.plist
- Sora/Utils/Loaders/JSController.swift
- Sora/Utils/Modules/Modules.swift
- Sora/Views/SearchView.swift
- Async JS with promise handling, custom javascript fetch
- New search Method
- New optional field for module
> New search results method

- Sora/Utils/Loaders/JSController.swift
- Sora/Views/MediaInfoView/MediaInfoView.swift
- Second method to fetch details with async js code
> New fetching details method

- Sora.xcodeproj/project.pbxproj
- Sora/Localizable.xcstrings
- Added German and Albanian localizations
> New localizations

- README.md
Just cleaned up some of the language to make it more direct and concise.
> Making the readme more concise

- Sora/Utils/MediaPlayer/CustomPlayer/CustomPlayer.swift
- Sora/Views/LibraryView/LibraryView.swift
- Sora/Views/MediaInfoView/EpisodeCell/EpisodeCell.swift
- Sora/Views/MediaInfoView/MediaInfoView.swift
didnt get to doing the ui cus...
cus
> Mark all previous watched option added

- Sora/Utils/MediaPlayer/CustomPlayer/CustomPlayer.swift
> fixed skip 85 seconds button for ipads

- Sora/Utils/MediaPlayer/CustomPlayer/CustomPlayer.swift
- Sora/Views/LibraryView/LibraryManager.swift
- Sora/Views/LibraryView/LibraryView.swift
- Sora/Views/MediaInfoView/MediaInfoView.swift
- Sora/Views/SettingsView/SettingsSubViews/SettingsViewPlayer.swift
- Sulfur.xcodeproj/project.pbxproj
fixed "Mark all previous" counting in the logger and removing a series from bookmarks when you open them from the home tab it no longer kicks you out
> bookmark logic

- Sora/Views/MediaInfoView/MediaInfoView.swift
Implemented detector for titles if the episodes for example have repeating number like: "Episode 13" then "Episode 1". Then title uses grouping by seasons.
> Implemented season seperator for tv shows

- Sora/Views/MediaInfoView/MediaInfoView.swift
> Implemented season seperator for tv shows 2

- Sora/Utils/MediaPlayer/CustomPlayer/CustomPlayer.swift
- Sora/Views/LibraryView/LibraryView.swift
> Added invisible control overlays + fixed overlapping images in portrait mode in library view

- Sora/Info.plist
- Sora/Utils/Extensions/JavaScriptCore+Extensions.swift
- Sora/Utils/JSLoader/JSController.swift
- Sora/Utils/Logger/Logger.swift
- Sulfur.xcodeproj/project.pbxproj
- Dedicated JavaScripteCore extension class
- Seperated JS logic from JSController class
- New available functions for js code: "atob()", "btoa()", "console.error()"
- New fetch method "fetchv2()" that can handle ".json()" &".text()" and possible to be expanded for post method support and more (new function for backwards compatibility)
- New Logger function to print in Debug mode to xcode console
> New JavaScriptCore Extension Class & more

- Sora/Utils/MediaPlayer/CustomPlayer/CustomPlayer.swift
- Sora/Views/MediaInfoView/MediaInfoView.swift
- Added toggle for subtitles
- Fixed mark all previous as watched in shows organized in seasons
- Made circle of double tap skipping not interactable
> Added toggle for subtitles + fixed mark all previous as watched in series organized in seasons

- Sora/Utils/MediaPlayer/CustomPlayer/Components/MusicProgressSlider.swift
- Sora/Utils/MediaPlayer/CustomPlayer/CustomPlayer.swift
- Sora/Views/SettingsView/SettingsSubViews/SettingsViewPlayer.swift
> as the commits say

- Sora/Utils/Extensions/JavaScriptCore+Extensions.swift
- "fetchv2" javascript function now supports proper methods, header and body support
- Backwards compatibility with previous implementation
- Defaults to GET if only url is provided
> Added POST, PUT, PATCH Support

- Sora/Utils/MediaPlayer/CustomPlayer/CustomPlayer.swift
- Sora/Views/MediaInfoView/MediaInfoView.swift
Added loading modal that has number of episode and cancel button that cancels fetching of stream and added feature that cancels fetching of stream when pressing on back to searchview button on mediainfoview + fixed error of double subtitles in custom player. Added dim mode button.
> Implementation of loading modal and dim mode

- Sora/Tracking Services/AniList/Mutations/AniListPushUpdates.swift
- Sora/Utils/MediaPlayer/CustomPlayer/Components/Double+Extension.swift
- Sora/Utils/MediaPlayer/CustomPlayer/Components/MusicProgressSlider.swift
- Sora/Utils/MediaPlayer/CustomPlayer/CustomPlayer.swift
- Sora/Views/MediaInfoView/EpisodeCell/EpisodeCell.swift
- Sora/Views/SearchView.swift
- Sora/Views/SettingsView/SettingsSubViews/SettingsViewPlayer.swift
Made buttons for skipping intros and outros of anime.
> Aniskip logic and basic buttons

- Sora/Utils/MediaPlayer/CustomPlayer/CustomPlayer.swift
- Sora/Views/SettingsView/SettingsSubViews/SettingsViewPlayer.swift
Added color picker for intro and outro segments in settingsviewplayer
> Color picker in settings for intro and outro segments

- Sora/Views/SettingsView/SettingsSubViews/SettingsViewAbout.swift
> LIFE OR DEATH PR

- Sora/Views/LibraryView/LibraryView.swift
- Sora/Views/MediaInfoView/MediaInfoView.swift
- Sora/Views/SettingsView/SettingsSubViews/SettingsViewModule.swift
https://github.com/user-attachments/assets/ee7dcad5-2a34-4525-a039-a57ed6fa9775
> POP THE CHAMPAGNE 🍾

- Sora/Localization/de.lproj/Localizable.strings
- Sora/Localization/kk.lproj/Localizable.strings
- Sora/Localization/sk.lproj/Localizable.strings
- Sora/Localization/sv.lproj/Localizable.strings
- Sora/Views/DownloadView.swift
- Sora/Views/LibraryView/AllBookmarks.swift
- Sora/Views/LibraryView/AllWatching.swift
- Sora/Views/LibraryView/BookmarkComponents/BookmarksDetailView.swift
- Sora/Views/MediaInfoView/MediaInfoView.swift
- Sora/Views/SearchView/SearchResultsGrid.swift
- Sora/Views/SettingsView/SettingsSubViews/SettingsViewAbout.swift
- Sora/Views/SettingsView/SettingsSubViews/SettingsViewGeneral.swift
- Sora/Views/SettingsView/SettingsView.swift
- Sulfur.xcodeproj/project.pbxproj
Languages:
- [German and Slovak](https://github.com/cranci1/Sora/commit/d0c48f8adab59b9bab6fb50a3a37681e0d0a4731)
- [Added Kazakh](https://github.com/cranci1/Sora/commit/f54d921f81580cdc06ea6f0a53e2e706452b84b6)
- [Seiike cant do shit dawggggg](https://github.com/cranci1/Sora/commit/a3e4925397db1f755b8188a8c474a6a4a3a71ce1)
- [Fix translator credits](https://github.com/cranci1/Sora/commit/559a1bd5ec4312d5e474c3cd42aab365f03f80a9)
Small fixes:
- [Added safari button for movie view](https://github.com/cranci1/Sora/commit/3d8a714e78d08522466ee43d22e813735df9dd79)
- [Search button for AllBookmarks and AllWatching](https://github.com/cranci1/Sora/commit/5fd44dd945e4619cf4028a1afdc77fe11a208226)
- [Delete all in download view without opening item (long …
> Whole Lotta Fixes (Carti reference) - Read description
